In [7]:
import torch

In [8]:
# Create *known* parameters
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [9]:
# Create train/test split
train_split = int(0.8 * len(X)) # 80% of data used for training set, 20% for testing
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [11]:
from torch import nn
#@ Building model:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights=nn.Parameter(torch.randn(1, dtype=torch.float), requires_grad=True)
    self.baises=nn.Parameter(torch.randn(1, dtype=torch.float), requires_grad=True)

  #@ Creating forward pass:
  def forward(self, X):
    return self.weights*X+self.baises


In [16]:
torch.manual_seed(42)
lr=LinearRegressionModel()
list(lr.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [18]:
#@ Making predictions with model:
with torch.inference_mode():
  y_pred=lr(X_test)

In [20]:
print(f'Number of Testing samples: {len(X_test)}')
print(f'Number of Prediction made: {len(y_pred)}')
print(f'Predicted Values:\n{y_pred}')

Number of Testing samples: 10
Number of Prediction made: 10
Predicted Values:
tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])
