In [1]:
import torch

In [4]:
#@ Initializing random tensor:

random=torch.rand(size=(3,4))
print(random)
print("Shape:", random.shape)
print("Dimension:", random.ndim)

tensor([[0.1517, 0.1749, 0.8834, 0.3792],
        [0.8692, 0.5005, 0.2712, 0.2382],
        [0.1807, 0.2102, 0.3321, 0.6326]])
Shape: torch.Size([3, 4])
Dimension: 2


In [5]:
#@ Filling tensors with Ones and Zeros:
zero_tensor=torch.zeros(size=(2,3))
ones_tensor=torch.ones(size=(1,3))

print(zero_tensor)
print('\n')
print(ones_tensor)



tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 1., 1.]])


In [6]:
#@ Creating tensors using range:

ten1=torch.arange(5, 20, 2)
print(ten1)

tensor([ 5,  7,  9, 11, 13, 15, 17, 19])


In [7]:
ten2=torch.zeros_like(ten1)
print(ten2)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


In [8]:
#@ Tensor Basic operations:
tensor=torch.tensor([1,2, 3])
tensor1 = tensor+1
tensor2=tensor*2
tensor3=tensor-1

print(tensor1)
print(tensor2)
print(tensor3)

tensor([2, 3, 4])
tensor([2, 4, 6])
tensor([0, 1, 2])


#### Multiplication is what you need:)

- For most part of neural network, we goona work with matrix multiplication. There are certain conditions for matrix Multiplication.

In [9]:
a=torch.tensor([1,2,4])
b=torch.tensor([[1, 2],  [2, 3]])

c=a*b
print(c)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [10]:
d=torch.ones_like(a)
f=a*d
print(f)

tensor([1, 2, 4])
