In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [3]:
import torch
torch.cuda.is_available()

True

In [5]:
#@ Setting device:
device='cuda' if torch.cuda.is_available() else 'cpu'

In [7]:
tensor=torch.tensor([1,2,3])
print(tensor, tensor.device)

#@ Moving tensor to GPU:
tensor_gpu=tensor.to(device)
print(tensor_gpu)


tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')


In [8]:
from torch import nn

In [9]:
# Create *known* parameters
weight = 0.7
bias = 0.3

# Create data
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [10]:
# Create train/test split
train_split = int(0.8 * len(X)) # 80% of data used for training set, 20% for testing
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [12]:
#@ Model Building:

class LinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights=nn.Parameter(torch.randn(1, dtype=torch.float), requires_grad=True)
    self.bias=nn.Parameter(torch.randn(1,  dtype=torch.float), reqiures_grad=True)

    def forward(self, x:torch.Tensor)->torch.Tensor:
      return self.weights*x+self.bias